import 'package:ai_marine_engine/state/osm_wrecks_provider.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('osmWrecksProvider', () {
    test('parses the bundled assets/osm_wrecks.json into WreckRecords',
        () async {
      // testWidgetsFlutterBinding.ensureInitialized() above gives the
      // rootBundle access to the project's pubspec assets.
      final container = ProviderContainer();
      addTearDown(container.dispose);

      final wrecks = await container.read(osmWrecksProvider.future);
      // Snapshot is regenerated by scripts/refresh_osm_wrecks.dart and
      // contains the FL bbox set — should never be empty.
      expect(wrecks, isNotEmpty);
      // Every record must have valid coords; the loader should not
      // emit synthetic blanks.
      for (final w in wrecks) {
        expect(w.id, isNotEmpty);
        expect(w.lat, inInclusiveRange(22.0, 32.0));
        expect(w.lon, inInclusiveRange(-92.0, -76.0));
      }
    });
  });
}
