import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../data/sources/osm/wreck_record.dart';

/// Bundled OSM wrecks loaded from `assets/osm_wrecks.json`. The
/// snapshot is generated by `scripts/refresh_osm_wrecks.dart` from the
/// Overpass API and bundled with the app, so this is a fully offline
/// data path — no network call at runtime.
///
/// Surfaced as a list for the chart marker layer and the
/// wreck-tap info card. The asset loads once at first watch and
/// the parsed result is cached for the rest of the session.
final osmWrecksProvider = FutureProvider<List<WreckRecord>>((ref) async {
  final raw = await rootBundle.loadString('assets/osm_wrecks.json');
  final json = jsonDecode(raw) as Map<String, dynamic>;
  final list = (json['wrecks'] as List).cast<Map<String, dynamic>>();
  return list.map(WreckRecord.fromJson).toList();
});
