import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../data/sources/osm/boat_ramp_record.dart';

/// Bundled OSM boat ramps loaded from `assets/osm_ramps.json`. The
/// snapshot is generated by `scripts/refresh_osm_ramps.dart` from the
/// Overpass API and bundled with the app, so this is a fully offline
/// data path — no network call at runtime.
///
/// Surfaced as a list for the chart marker layer, the ramp-tap info
/// card, and (slice 13a) the trip-planner anchor picker.
final osmRampsProvider = FutureProvider<List<BoatRampRecord>>((ref) async {
  final raw = await rootBundle.loadString('assets/osm_ramps.json');
  final json = jsonDecode(raw) as Map<String, dynamic>;
  final list = (json['ramps'] as List).cast<Map<String, dynamic>>();
  return list.map(BoatRampRecord.fromJson).toList();
});
