/// Refresh `assets/osm_ramps.json` from the live OpenStreetMap
/// Overpass API, filtered to the v1 Florida coverage bbox.
///
/// Run with: `fvm dart run scripts/refresh_osm_ramps.dart`
///
/// Captures `leisure=slipway` (primary OSM tag for boat ramps) and the
/// less-common `amenity=boat_ramp`. The trip-planner UX uses these as
/// the anchor for the user's trip area — pick a ramp, define the
/// fishable bbox around it.
///
/// Coverage caveat: OSM ramps are community-contributed. Public state
/// and county ramps are usually well-mapped; private marina ramps are
/// hit-or-miss. For authoritative FL ramps the FWC publishes an
/// official ArcGIS dataset (their endpoints are flaky enough that
/// OSM-first was the cleaner v1 path — see slice-planning notes).
library;

import 'dart:convert';
import 'dart:io';

/// Inclusive bbox matching the NDBC + wrecks refresh. Keeps every
/// bundled feature on the same coverage envelope.
const _minLat = 22.0;
const _maxLat = 32.0;
const _minLon = -92.0;
const _maxLon = -76.0;

const _overpassUrl = 'https://overpass-api.de/api/interpreter';
const _outputPath = 'assets/osm_ramps.json';

Future<void> main() async {
  // Pull both common ramp taggings (slipways and the rarer
  // amenity=boat_ramp). Use `out center` so way-shaped ramps still get
  // a single representative coordinate for the marker layer.
  const query = '''
[out:json][timeout:60];
(
  node["leisure"="slipway"]($_minLat,$_minLon,$_maxLat,$_maxLon);
  way["leisure"="slipway"]($_minLat,$_minLon,$_maxLat,$_maxLon);
  node["amenity"="boat_ramp"]($_minLat,$_minLon,$_maxLat,$_maxLon);
  way["amenity"="boat_ramp"]($_minLat,$_minLon,$_maxLat,$_maxLon);
);
out center;
''';

  stdout.writeln('Querying $_overpassUrl …');
  final body = await _post(_overpassUrl, query);
  final json = jsonDecode(body) as Map<String, dynamic>;
  final elements = (json['elements'] as List).cast<Map<String, dynamic>>();

  final ramps = <_Ramp>[];
  var droppedPrivate = 0;
  for (final e in elements) {
    final lat = _coordOf(e, 'lat');
    final lon = _coordOf(e, 'lon');
    if (lat == null || lon == null) continue;
    final tags =
        (e['tags'] as Map<String, dynamic>? ?? {}).cast<String, String>();
    // Drop explicitly-private ramps — trip planning is for public
    // launches. Untagged ramps stay in (vast majority of OSM ramps
    // simply lack an `access` tag — we trust the OSM bias toward
    // public features).
    if (tags['access'] == 'private') {
      droppedPrivate++;
      continue;
    }
    ramps.add(
      _Ramp(
        id: '${e['type']}/${e['id']}',
        name: tags['name'],
        access: tags['access'],
        fee: tags['fee'],
        surface: tags['surface'],
        lat: lat,
        lon: lon,
      ),
    );
  }
  ramps.sort((a, b) => a.id.compareTo(b.id));

  stdout.writeln(
    'Got ${ramps.length} ramps inside ($_minLat..$_maxLat, $_minLon..$_maxLon) '
    '(dropped $droppedPrivate private).',
  );

  final out = const JsonEncoder.withIndent('  ').convert({
    'schemaVersion': '1.0',
    '_comment':
        'OSM boat ramps (leisure=slipway / amenity=boat_ramp) within v1 '
            'Florida coverage bbox. Generated by '
            'scripts/refresh_osm_ramps.dart from $_overpassUrl. Coverage '
            'is community-maintained — re-run before each release.',
    '_generatedAt': DateTime.now().toUtc().toIso8601String(),
    '_bbox': {
      'minLat': _minLat,
      'maxLat': _maxLat,
      'minLon': _minLon,
      'maxLon': _maxLon,
    },
    'ramps': [
      for (final r in ramps)
        {
          'id': r.id,
          if (r.name != null) 'name': r.name,
          if (r.access != null) 'access': r.access,
          if (r.fee != null) 'fee': r.fee,
          if (r.surface != null) 'surface': r.surface,
          'lat': r.lat,
          'lon': r.lon,
        },
    ],
  });

  await File(_outputPath).writeAsString('$out\n');
  stdout.writeln('Wrote $_outputPath');
}

/// Pulls lat/lon from either a node element (top-level lat/lon) or a
/// way/relation element (`center.lat` / `center.lon` from `out center`).
double? _coordOf(Map<String, dynamic> e, String key) {
  final direct = e[key];
  if (direct is num) return direct.toDouble();
  final center = e['center'] as Map<String, dynamic>?;
  final c = center?[key];
  if (c is num) return c.toDouble();
  return null;
}

/// Overpass requires a meaningful User-Agent and accepts the query
/// either as raw POST body or `data=` form-encoded. Form-encoded path
/// is the most reliable across mirrors.
Future<String> _post(String url, String query) async {
  final client = HttpClient();
  try {
    final req = await client.postUrl(Uri.parse(url));
    req.headers.set(
      HttpHeaders.userAgentHeader,
      'ai_marine_engine/0.1 (refresh_osm_ramps; '
      'https://github.com/pjaelmore/AI-Marine)',
    );
    req.headers.set(HttpHeaders.acceptHeader, 'application/json');
    req.headers.contentType =
        ContentType('application', 'x-www-form-urlencoded', charset: 'utf-8');
    final encoded = utf8.encode('data=${Uri.encodeQueryComponent(query)}');
    req.contentLength = encoded.length;
    req.add(encoded);
    final res = await req.close();
    if (res.statusCode != 200) {
      final body = await res.transform(utf8.decoder).join();
      throw HttpException(
        'POST $url returned ${res.statusCode}: '
        '${body.substring(0, body.length.clamp(0, 200))}',
      );
    }
    return await res.transform(utf8.decoder).join();
  } finally {
    client.close();
  }
}

class _Ramp {
  _Ramp({
    required this.id,
    required this.lat,
    required this.lon,
    this.name,
    this.access,
    this.fee,
    this.surface,
  });

  final String id;
  final String? name;
  final String? access;
  final String? fee;
  final String? surface;
  final double lat;
  final double lon;
}
