/// Refresh `assets/osm_wrecks.json` from the live OpenStreetMap
/// Overpass API, filtered to the v1 Florida coverage bbox.
///
/// Run with: `fvm dart run scripts/refresh_osm_wrecks.dart`
///
/// Why a snapshot and not live-fetch at startup: same rationale as the
/// NDBC station list. Wreck features change slowly (years). Bundling a
/// snapshot keeps the app offline-first and removes the Overpass
/// dependency from cold start. Re-run before each release to pick up
/// new community contributions.
///
/// Coverage caveat: OSM wrecks are community-contributed via the
/// `seamark:type=wreck` tag. Coverage is partial — popular dive sites
/// and named historic wrecks are well-mapped, obscure ones may be
/// missing. For chartplotter-grade wreck coverage you need NOAA's
/// official ENC data (scoped for v1.5+ MBTiles bundling).
library;

import 'dart:convert';
import 'dart:io';

/// Inclusive bbox matching the NDBC station refresh — keeps the wreck
/// markers and buoy markers on the same coverage envelope.
const _minLat = 22.0;
const _maxLat = 32.0;
const _minLon = -92.0;
const _maxLon = -76.0;

const _overpassUrl = 'https://overpass-api.de/api/interpreter';
const _outputPath = 'assets/osm_wrecks.json';

Future<void> main() async {
  // Filter at the Overpass level to require either
  // `seamark:wreck:category` OR `seamark:wreck:depth` to be set —
  // bare `seamark:type=wreck` taggings often land on dry land
  // (beached/preserved wrecks, museum ships, marina decorations) or
  // on inland features. Real underwater chart wrecks almost always
  // have at least one of category or depth populated.
  const query = '''
[out:json][timeout:60];
(
  node["seamark:type"="wreck"]["seamark:wreck:category"]($_minLat,$_minLon,$_maxLat,$_maxLon);
  node["seamark:type"="wreck"]["seamark:wreck:depth"]($_minLat,$_minLon,$_maxLat,$_maxLon);
  way["seamark:type"="wreck"]["seamark:wreck:category"]($_minLat,$_minLon,$_maxLat,$_maxLon);
  way["seamark:type"="wreck"]["seamark:wreck:depth"]($_minLat,$_minLon,$_maxLat,$_maxLon);
);
out center;
''';

  stdout.writeln('Querying $_overpassUrl …');
  final body = await _post(_overpassUrl, query);
  final json = jsonDecode(body) as Map<String, dynamic>;
  final elements = (json['elements'] as List).cast<Map<String, dynamic>>();

  final wrecks = <_Wreck>[];
  for (final e in elements) {
    final lat = _coordOf(e, 'lat');
    final lon = _coordOf(e, 'lon');
    if (lat == null || lon == null) continue;
    final tags =
        (e['tags'] as Map<String, dynamic>? ?? {}).cast<String, String>();
    wrecks.add(
      _Wreck(
        id: '${e['type']}/${e['id']}',
        name: tags['name'] ?? tags['seamark:name'],
        category: tags['seamark:wreck:category'],
        depthM: double.tryParse(tags['seamark:wreck:depth'] ?? ''),
        lat: lat,
        lon: lon,
      ),
    );
  }
  wrecks.sort((a, b) => a.id.compareTo(b.id));

  stdout.writeln(
    'Got ${wrecks.length} wrecks inside ($_minLat..$_maxLat, $_minLon..$_maxLon).',
  );

  final out = const JsonEncoder.withIndent('  ').convert({
    'schemaVersion': '1.0',
    '_comment':
        'OSM wrecks (`seamark:type=wreck`) within v1 Florida coverage bbox. '
            'Generated by scripts/refresh_osm_wrecks.dart from $_overpassUrl. '
            'Coverage is community-maintained — re-run before each release.',
    '_generatedAt': DateTime.now().toUtc().toIso8601String(),
    '_bbox': {
      'minLat': _minLat,
      'maxLat': _maxLat,
      'minLon': _minLon,
      'maxLon': _maxLon,
    },
    'wrecks': [
      for (final w in wrecks)
        {
          'id': w.id,
          if (w.name != null) 'name': w.name,
          if (w.category != null) 'category': w.category,
          if (w.depthM != null) 'depthM': w.depthM,
          'lat': w.lat,
          'lon': w.lon,
        },
    ],
  });

  await File(_outputPath).writeAsString('$out\n');
  stdout.writeln('Wrote $_outputPath');
}

/// Pulls lat/lon from either a node element (top-level lat/lon) or a
/// way/relation element (under `center.lat` / `center.lon` because we
/// requested `out center`).
double? _coordOf(Map<String, dynamic> e, String key) {
  final direct = e[key];
  if (direct is num) return direct.toDouble();
  final center = e['center'] as Map<String, dynamic>?;
  final c = center?[key];
  if (c is num) return c.toDouble();
  return null;
}

/// Overpass requires a meaningful User-Agent (it blocks default Dart
/// agents to discourage abuse) and accepts the query either as a raw
/// POST body or as `data=` form-encoded. We use the form-encoded path
/// because some Overpass mirrors reject raw bodies with 400.
Future<String> _post(String url, String query) async {
  final client = HttpClient();
  try {
    final req = await client.postUrl(Uri.parse(url));
    req.headers.set(
      HttpHeaders.userAgentHeader,
      'ai_marine_engine/0.1 (refresh_osm_wrecks; '
      'https://github.com/pjaelmore/AI-Marine)',
    );
    req.headers.set(HttpHeaders.acceptHeader, 'application/json');
    req.headers.contentType =
        ContentType('application', 'x-www-form-urlencoded', charset: 'utf-8');
    final encoded = utf8.encode('data=${Uri.encodeQueryComponent(query)}');
    req.contentLength = encoded.length;
    req.add(encoded);
    final res = await req.close();
    if (res.statusCode != 200) {
      final body = await res.transform(utf8.decoder).join();
      throw HttpException(
        'POST $url returned ${res.statusCode}: '
        '${body.substring(0, body.length.clamp(0, 200))}',
      );
    }
    return await res.transform(utf8.decoder).join();
  } finally {
    client.close();
  }
}

class _Wreck {
  _Wreck({
    required this.id,
    required this.lat,
    required this.lon,
    this.name,
    this.category,
    this.depthM,
  });

  final String id;
  final String? name;
  final String? category;
  final double? depthM;
  final double lat;
  final double lon;
}
